{% set name = "pytest-benchmark" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd0adf68516eea7ac212b78a7eb6fc3373865507de8562bb3bfff2f2f852cc63

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - py.test-benchmark = pytest_benchmark.cli:main
    - pytest-benchmark = pytest_benchmark.cli:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pytest >=3.8
    - py-cpuinfo

test:
  imports:
    - pytest_benchmark
  commands:
    - py.test --traceconfig | grep pytest-benchmark-{{ version }}
    - pytest-benchmark --help
    - py.test-benchmark --help

about:
  home: https://github.com/ionelmc/pytest-benchmark
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A py.test fixture for benchmarking code

extra:
  recipe-maintainers:
    - astrojuanlu
    - esloch
