{% set name = "pytest-benchmark" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ea661cdc292e8231f7cd4c10b0319e56a2118e2c09d9f50e1b3d150d2aca105

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - py.test-benchmark = pytest_benchmark.cli:main
    - pytest-benchmark = pytest_benchmark.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytest >=3.8
    - py-cpuinfo

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_benchmark
  commands:
    - py.test --traceconfig | grep pytest-benchmark-{{ version }}
    - pytest-benchmark --help
    - py.test-benchmark --help

about:
  home: https://github.com/ionelmc/pytest-benchmark
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A py.test fixture for benchmarking code

extra:
  recipe-maintainers:
    - astrojuanlu
    - esloch
